# Generated by Django 3.1.7 on 2021-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captured_image',
            name='Main_Img',
        ),
        migrations.AddField(
            model_name='captured_image',
            name='main_image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
